base_url = "https://nulisajadulu.web.id"
title = "Nulis Aja Dulu"
description = "Kadang nulis yang penting, kadang yang penting nulis."
author = "akhy"
theme = "tabi"
generate_feeds = true
compile_sass = true
minify_html = true
build_search_index = false
taxonomies = [{name = "tags", feed = true}]

[markdown]
highlight_code = true
highlight_theme = "css"

[extra]
theme_switcher = false
default_theme = "dark"
skin = "lavender"
favicon = "favicon.ico"
stylesheets = [ "override.css" ]
menu = [
  { name = "blog", url = "posts", trailing_slash = true },
  { name = "tentang", url = "about", trailing_slash = true },
]
allowed_domains = [
  { directive = "font-src", domains = ["'self'", "data:"] },
  { directive = "img-src", domains = ["'self'", "https://*", "data:"] },
  { directive = "media-src", domains = ["'self'", "https://cdn.jsdelivr.net/"] },
  { directive = "script-src", domains = ["'self'", "https://*.mdgrd.net"] },
  { directive = "style-src", domains = ["'self'", "https://*.mdgrd.net"] },
  { directive = "frame-src", domains = ["player.vimeo.com", "https://www.youtube-nocookie.com"] },
]
socials = [
  { name = "twitter/x", url = "https://x.com/akhy", icon = "x" },
  { name = "mastodon", url = "https://mstdn.io/@akhy", icon = "mastodon" },
  { name = "pixelfed", url = "https://pixelfed.social/akhy", icon = "pixelfed" },
]

[extra.hcard]
enable = true
avatar = "img/peperonny.png"

[extra.isso]
enabled_for_all_posts = true
endpoint_url = "https://comentario.mdgrd.net"

[extra.analytics]
service = "umami"
id = "c3493979-8ec7-420e-a2a8-6d270fc6c2d1"

[extra.webmentions]
enable = true
domain = "nulisajadulu.web.id"

