base_url = "https://nulisajadulu.web.id"
title = "Nulis Aja Dulu"
description = "Kadang nulis yang penting, kadang yang penting nulis."
author = "Pepe Ronny"
theme = "tabi"
generate_feeds = true
compile_sass = true
minify_html = true
build_search_index = false
taxonomies = [{name = "tags", feed = true}]

[markdown]
highlight_code = true
highlight_theme = "css"

[extra]
theme_switcher = false
default_theme = "dark"
skin = "lavender"
stylesheets = [ "override.css" ]
menu = [
  { name = "blog", url = "posts", trailing_slash = true },
  { name = "tentang", url = "about", trailing_slash = true },
]
allowed_domains = [
  { directive = "font-src", domains = ["'self'", "data:"] },
  { directive = "img-src", domains = ["'self'", "https://*", "data:"] },
  { directive = "media-src", domains = ["'self'", "https://cdn.jsdelivr.net/"] },
  { directive = "script-src", domains = ["'self'", "https://*.mdgrd.net"] },
  { directive = "style-src", domains = ["'self'", "https://*.mdgrd.net"] },
  { directive = "frame-src", domains = ["player.vimeo.com", "https://www.youtube-nocookie.com"] },
]

[extra.hcard]
enable = true
avatar = "img/peperonny.png"

[extra.isso]
enabled_for_all_posts = true
endpoint_url = "https://comentario.mdgrd.net"
